# Site settings
title: Hillbilly Nerd - A country bumpkin's adventures into technology.
email: mgfreshour@gmail.com
description: >
  A country bumpkin's adventures into technology.  Random articles on programming
  and other things that interest me.
baseurl: ""
url: "http://mgfreshour.github.io"
fixedNav: 'true' # true or false
theme: green # green, blue, orange, purple, grey
twitterUsername:
githubUsername: mgfreshour
dribbbleUsername:
codepenUsername:

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
highlighter: rouge
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
